import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, ApiError } from '../lib/api';
import type { Kid } from '../lib/types';
import { MemberAvatar, PageTag, Wordmark } from '../ui/primitives';
import { PinPad } from '../ui/PinPad';
import { Skeleton } from '../ui/Skeleton';
import { EmptyState } from '../ui/EmptyState';

type PairResponse = {
  family: { id: string; name: string };
  device: { id: string; label: string; token: string; expiresAt: string };
};

const DEVICE_SESSION_KEY = 'cb_device_session';

/**
 * The "kid sign-in" path. The device must be paired to a family before the
 * kid roster can be shown — pairing is via a 6-digit code generated by a
 * parent in `AdminFamily → Paired devices` (PR 4 wires the form on this
 * screen; right now an unpaired device sees an explanatory empty state).
 */
export function KidPinScreen() {
  const [familyId, setFamilyId] = useState<string | null>(
    typeof window !== 'undefined' ? localStorage.getItem('cb_family_id') : null,
  );
  const [selectedKid, setSelectedKid] = useState<Kid | null>(null);
  const [pin, setPin] = useState('');
  const qc = useQueryClient();

  const kidsQ = useQuery({
    queryKey: ['kid-roster', familyId],
    queryFn: async () => {
      const r = await api.get<{ kids: Kid[] }>(`/api/auth/family/${familyId}/kids`);
      return r.kids;
    },
    enabled: !!familyId,
  });

  const loginMut = useMutation({
    mutationFn: (submittedPin: string) =>
      api.post('/api/auth/kid-login', { kidId: selectedKid!.id, pin: submittedPin }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['session'] });
    },
  });

  // Reset PIN on a failed attempt so the next attempt is clean.
  useEffect(() => {
    if (loginMut.error) setPin('');
  }, [loginMut.error]);

  const layout = (children: React.ReactNode) => (
    <div className="safe-pt safe-pb flex min-h-screen flex-col px-4 py-6 sm:px-8 sm:py-8">
      <header className="mb-6 flex items-start justify-between sm:mb-10">
        <Wordmark size="lg" />
        <PageTag index={4} label="PIN SIGN-IN" title="Who's here?" />
      </header>
      <div className="flex flex-1 items-start justify-center">{children}</div>
      <nav
        className="mt-8 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 text-center text-xs text-ink-500"
        aria-label="Legal"
      >
        <Link to="/privacy" className="hover:text-ink-900 hover:underline">
          Privacy
        </Link>
        <span aria-hidden="true">·</span>
        <Link to="/terms" className="hover:text-ink-900 hover:underline">
          Terms
        </Link>
        <span aria-hidden="true">·</span>
        <a
          href="mailto:support@choreboard.io"
          className="hover:text-ink-900 hover:underline"
        >
          support@choreboard.io
        </a>
      </nav>
    </div>
  );

  if (!familyId) {
    return layout(<PairingCodeForm onPaired={(fam) => setFamilyId(fam.id)} />);
  }

  if (!selectedKid) {
    return layout(
      <div className="w-full max-w-5xl">
        <div className="mb-6 flex flex-col items-stretch gap-3 sm:flex-row sm:items-end sm:justify-between sm:gap-6">
          <div>
            <div className="page-tag mb-1">WELCOME</div>
            <h2 className="font-display text-3xl font-extrabold tracking-tight sm:text-5xl">
              Who&apos;s here?
            </h2>
          </div>
          <button
            className="pill-tap self-start whitespace-nowrap sm:self-end"
            onClick={() => {
              localStorage.removeItem('cb_family_id');
              setFamilyId(null);
            }}
          >
            Switch family
          </button>
        </div>
        {kidsQ.isLoading && (
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4 lg:grid-cols-4">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="card flex flex-col items-center gap-3 p-4 sm:p-5">
                <Skeleton width={80} height={80} radius={999} />
                <Skeleton width="60%" height={14} />
                <Skeleton width="40%" height={10} />
              </div>
            ))}
          </div>
        )}
        {kidsQ.data && kidsQ.data.length === 0 && (
          <div className="card p-6">
            <EmptyState
              illustration="kids"
              title="No kids set up yet"
              body="Ask a parent to add you in the family admin screen."
            />
          </div>
        )}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 3xl:grid-cols-7">
          {kidsQ.data?.map((k) => (
            <button
              key={k.id}
              onClick={() => setSelectedKid(k)}
              className="card group flex flex-col items-center gap-3 p-4 transition active:translate-y-px hover:-translate-y-0.5 sm:p-5 lg:p-6"
            >
              <MemberAvatar name={k.name} color={k.color} size="xl" />
              <span className="font-display text-base font-extrabold sm:text-lg lg:text-xl">
                {k.name}
              </span>
              <span className="page-tag">TAP TO SIGN IN</span>
            </button>
          ))}
        </div>
      </div>,
    );
  }

  return layout(
    <div className="w-full max-w-md text-center sm:max-w-lg">
      <button
        className="pill-tap mb-4"
        onClick={() => {
          setSelectedKid(null);
          setPin('');
        }}
      >
        ← Not me
      </button>
      <div className="flex flex-col items-center gap-3">
        <div className="page-tag">WELCOME BACK</div>
        <MemberAvatar name={selectedKid.name} color={selectedKid.color} size="2xl" />
        <span className="font-display text-3xl font-extrabold tracking-tight sm:text-4xl">
          {selectedKid.name}
        </span>
      </div>

      <div className="my-6 sm:my-8">
        <PinPad
          value={pin}
          onChange={setPin}
          onComplete={(submitted) => {
            if (selectedKid && !loginMut.isPending) loginMut.mutate(submitted);
          }}
        />
      </div>

      {loginMut.error instanceof ApiError && (
        <p className="mt-4 rounded-lg bg-accent-red/10 px-3 py-2 text-sm text-accent-red ring-1 ring-accent-red/30">
          {loginMut.error.message === 'invalid_pin'
            ? 'Wrong PIN. Try again.'
            : loginMut.error.message}
        </p>
      )}
      {loginMut.isPending && (
        <p className="mt-4 text-sm font-semibold text-ink-500">Signing in…</p>
      )}
    </div>,
  );
}

/**
 * Six-digit pairing-code form, rendered when the device has no
 * `cb_family_id` cached. On success we cache the family id (so subsequent
 * visits skip this step) and the device session token (kept for future
 * "tell the server which device this is" use cases). The kid avatar grid
 * mounts immediately afterwards.
 */
function PairingCodeForm({ onPaired }: { onPaired: (fam: { id: string; name: string }) => void }) {
  const [code, setCode] = useState('');
  const pair = useMutation({
    mutationFn: () =>
      api.post<PairResponse>('/api/auth/pair', { code }),
    onSuccess: (data) => {
      try {
        localStorage.setItem('cb_family_id', data.family.id);
        localStorage.setItem(
          DEVICE_SESSION_KEY,
          JSON.stringify({
            token: data.device.token,
            expiresAt: data.device.expiresAt,
            familyId: data.family.id,
            label: data.device.label,
          }),
        );
      } catch {
        // localStorage failures are non-fatal — the in-memory familyId still
        // works for this session; pairing again next time is the recovery.
      }
      onPaired(data.family);
    },
  });

  const onChange = (next: string) => {
    const digits = next.replace(/\D/g, '').slice(0, 6);
    setCode(digits);
  };

  return (
    <div className="card w-full max-w-md p-6 sm:p-8">
      <div className="mb-2 flex items-center justify-between gap-3">
        <div className="page-tag">PAIR THIS DEVICE</div>
        <Link to="/" className="pill-tap whitespace-nowrap">
          Parent sign-in →
        </Link>
      </div>
      <h1 className="font-display text-2xl font-extrabold tracking-tight sm:text-3xl">
        Enter the 6-digit code
      </h1>
      <p className="mt-2 text-sm text-ink-500">
        Ask a parent to open <strong>Admin → Family → Paired devices</strong> on
        their phone and tap <strong>Pair a new device</strong>.
      </p>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          if (code.length === 6 && !pair.isPending) pair.mutate();
        }}
        className="mt-5 flex flex-col gap-3"
      >
        <input
          autoFocus
          inputMode="numeric"
          pattern="\d{6}"
          maxLength={6}
          aria-label="Pairing code"
          value={code}
          onChange={(e) => onChange(e.target.value)}
          className="input text-center font-display text-3xl font-extrabold tabular-nums tracking-[0.18em]"
          placeholder="••••••"
        />
        <button
          type="submit"
          className="btn-primary w-full"
          disabled={code.length !== 6 || pair.isPending}
        >
          {pair.isPending ? 'Pairing…' : 'Continue'}
        </button>
        {pair.error instanceof ApiError && (
          <p className="rounded-lg bg-accent-red/10 px-3 py-2 text-sm text-accent-red ring-1 ring-accent-red/30">
            {pair.error.message === 'pairing_code_invalid'
              ? "That code didn't work. It may have expired or already been used — ask a parent for a new one."
              : pair.error.message}
          </p>
        )}
      </form>
    </div>
  );
}
